### PR TITLE
Adding Networking section & Netris

### PR DESCRIPTION
**Pull request by ixodie**
Adding a networking section for items that are non-CNI
Added Netris for physical networking operations via k8s API

### CODE REVIEW

**Comment by ixodie** [comment]
@juandiegopalomino please approve

**Comment by francissimo** [comment]
@Nico385412 
[Francissimon](www.keepgitlab..com)

**Comment by ixodie** [comment]
Hello @Nico385412 is there anything else I need to do here?

**Comment by Nico385412** [comment]
Sounds good to me. But i dot not have any rights to approve your pull request 😅

**Comment by ixodie** [comment]
Who has write access?

**Comment by ixodie** [comment]
This will apparently not be added to this list because the repo maintainer is a corporation and they do not currently use Netris.

**Pull request closed without merging**
